# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages
matrix:
  include:
  - r: release
    after_success:
    - Rscript -e 'covr::codecov()'
    # TODO: revert once rmarkdown fixed
    before_cache: Rscript -e 'remotes::install_github("r-lib/pkgdown")'
    # before_cache: Rscript -e 'remotes::install_github("rstudio/rmarkdown"); remotes::install_cran("pkgdown")'
    deploy:
      provider: script
      script: Rscript -e 'pkgdown::deploy_site_github()'
      github_token: $GITHUB_TOKEN
      skip_cleanup: true
      keep_history: true
      on:
        branch: master

branches:
  except:
  - dev
